accounts:
  - 中金点睛
  - 郭磊宏观茶座
  - 留富兵法
  - 招商宏观静思录
  - 申万宏源宏观
  - 张伟经济观察
  - 诚意策略通财
  - 业谈债市
  - 泓观卓见
  - 一凌策略研究
  - 冠南固收视野
  - 中金宏观
  - 郁言债市
  - 宏观田点
  - 珮珊债券研究
  - 华泰证券宏观研究
  - 招商证券基金评价
  - XYQuantResearch
  - 量化方程式
  - 中国银河宏观
  - 招商证券策略研究
